FROM node:16

WORKDIR /core

COPY . /core

RUN yarn install --production
RUN yarn add gnomon

# the app needs to be built before start for static env variables but this caches a first build
RUN npm run build

CMD npm run build && npm start
