FROM node:16

RUN apt update && apt install vim -y

WORKDIR /core/ihelp-app/config
COPY ihelp-app/config/* ./
RUN yarn install

WORKDIR /core/ihelp-contracts

COPY ihelp-contracts/hardhat.config.js ./
COPY ihelp-contracts/package.json ./
COPY ihelp-contracts/networks networks

# COPY ihelp-contracts/node_modules ./node_modules
RUN yarn install

WORKDIR /core/ihelp-contracts
COPY ihelp-contracts/scripts scripts

WORKDIR /core/ihelp-contracts/scripts

CMD bash
