FROM postgres:14

RUN echo "#!/bin/bash" > /entry.sh
RUN echo "set -x" > /entry.sh
RUN echo "gosu postgres pg_resetwal -f /var/lib/postgresql/data" >> /entry.sh
RUN echo "/usr/local/bin/docker-entrypoint.sh postgres" >> /entry.sh
RUN chmod 777 entry.sh

CMD [ "/bin/bash", "/entry.sh" ]
