FROM node:16

WORKDIR /core

COPY . /core

RUN yarn install --production
RUN yarn add gnomon

# build the client custom web3modal
RUN cd src/modules/web3modal && yarn install && yarn build && cd ../../../

# the app needs to be built before start for static env variables but this caches a first build
RUN npm run build

CMD npm run build && npm start
