
name: Create Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'
jobs:
  release-ihelp-server:
      env:
        docker_repo: ihelp-server
        service: server
        docker_tag: ${{ github.ref_name }}
      runs-on: ubuntu-latest
      steps:
        - name: Check out services repository
          uses: actions/checkout@v2
        - name: Prepare the services environment
          run: /bin/bash servicePrep.sh
        - name: Build the Docker image
          run: ./serviceBuild.sh ${{ env.service }}
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: turbinex
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Push the Docker image to Docker Hub
          run: docker push turbinex/${{ env.docker_repo }}:${{ env.docker_tag }}
